TOOLS_DMAIC_MATRIX = [
    {"id": "muestreo", "name": "Muestreo", "phases": ["M", "I"]},
    {"id": "risk_analysis", "name": "Análisis de riesgos", "phases": ["I"]},
    {"id": "anova", "name": "Analisis de varianza (ANOVA)", "phases": ["A"]},
    {"id": "cost_tree", "name": "Arbol de costos", "phases": ["D", "M"]},
    {"id": "structure_tree", "name": "Arbol de estructura", "phases": ["M"]},
    {"id": "boxplot", "name": "Box Plot (Diagrama de caja)", "phases": ["M", "A"]},
    {"id": "brainstorming", "name": "Brainstorming", "phases": ["D", "M", "A"]},
    {"id": "capability", "name": "Capacidades / Z bench", "phases": ["M", "I", "C"]},
    {"id": "spc", "name": "CEP (control estadístico Procesos)", "phases": ["C"]},
    {"id": "gantt", "name": "Cronograma / Gráfico de Gantt", "phases": ["D", "M", "A", "I", "C"]},
    {"id": "cost_benefit", "name": "Costo - Beneficio", "phases": ["D", "I", "C"]},
    {"id": "affinity", "name": "Diagrama de afinidades", "phases": ["D", "A"]},
    {"id": "scatter", "name": "Diagrama de dispersión / Scatter Diagram", "phases": ["M"]},
    {"id": "radar", "name": "Diagrama de Radar / Radar Chart", "phases": ["M"]},
    {"id": "doe", "name": "Diseño de experimentos (DOE)", "phases": ["A", "I"]},
    {"id": "interviews", "name": "Entrevistas", "phases": ["M", "A"]},
    {"id": "ishikawa", "name": "Espina de pescado", "phases": ["A"]},
    {"id": "stratification", "name": "Estratificaciones", "phases": ["M", "A"]},
    {"id": "fmea", "name": "Análisis de Modo y Efecto de Falla (FMEA)", "phases": ["A", "I"]},
    {"id": "gage_rr", "name": "Gage R&R", "phases": ["M"]},
    {"id": "run_chart", "name": "Gráfico de series de tiempo - Run Chart", "phases": ["M", "A"]},
    {"id": "histogram", "name": "Histograma", "phases": ["M", "A"]},
    {"id": "conf_interval", "name": "Intervalo de Confianza", "phases": ["M", "A", "I", "C"]},
    {"id": "process_map", "name": "Mapa de procesos", "phases": ["D", "A"]},
    {"id": "ce_matrix", "name": "Matriz de Causa Efecto", "phases": ["A"]},
    {"id": "raci", "name": "Matriz de responsabilidades", "phases": ["D", "C"]},
    {"id": "pareto", "name": "Pareto / ABC", "phases": ["M", "A", "I"]},
    {"id": "control_plan", "name": "Plan de Control", "phases": ["C"]},
    {"id": "qfd", "name": "La casa de calidad (QFD)", "phases": ["D"]},
    {"id": "regression", "name": "Regresión", "phases": ["A", "I"]},
    {"id": "rsm", "name": "Superficie de respuesta (RSM)", "phases": ["I"]},
    {"id": "hypothesis", "name": "Prueba de hipótesis", "phases": ["A"]},
    {"id": "normality", "name": "Prueba de normalidad", "phases": ["M"]},
    {"id": "chi_square", "name": "Prueba de Chi-quadrado", "phases": ["A"]},
    {"id": "bsc", "name": "Balanced Scorecard", "phases": ["C"]},
    {"id": "pmi", "name": "PMI", "phases": ["D","C"]}
]